### ISSUE TITLE
Signing in doesn't require credentials after signing out

### ISSUE THREAD

**Issue by zemien** [microsoftgraph/aspnetcore-apponlytoken-webhooks-sample#3] opened 2017-07-02 08:42 UTC
I'm perplexed as to why I wasn't prompted for credentials when I try to sign in after signing out. To be explicit:

1. Run web app in Incognito
2. Sign In - redirects to AAD login page and I enter correct credentials
3. Sign Out - redirects to home page and the upper-right shows 'Sign In' again
4. Sign In - immediately signs me in as the same user without prompting credentials

Does this behaviour have anything to do with the SampleTokenCache?

**Comment by jamescro** [comment] 2017-07-05 16:39
I believe that this is happening because of the in-memory token cache. Do you see this behavior if you stop running the sample, close the browser, and then run it again?

**Comment by jamescro** [comment] 2017-07-05 22:50
I've verified this behavior. It does have to do with the way that the SampleTokenCache is implemented. If you want to log in with a different account, you can close the browser and relaunch the application. 
The token cache in this sample is intended for demonstration purposes, and this sample calls it out as not production-ready, so a more robust caching mechanism would likely alter this behavior (assuming that it is undesired). 
Closing since the sample is behaving as designed. Please reopen, though if you can't log in as a different user after relaunching the application.

**Closed by jamescro** 2017-07-05 22:50 UTC
